import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/providers/Providers';

export const metadata: Metadata = {
      title: 'Baby Food',
      description: 'Generated by create next app',
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html lang="en" className="scroll-smooth">
                  <body>
                        <Providers>{children}</Providers>
                  </body>
            </html>
      );
}
